services:

  alloy:
    image: grafana/alloy:${ALLOY_VERSION}
    hostname: alloy
    container_name: alloy
    ports:
      - "12345:12345"
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./alloy/config.alloy
        target: /etc/alloy/config.alloy
        read_only: true
      - type: volume
        source: volume-metricmind-alloy
        target: /var/lib/alloy/data
    networks:
      - metricmind-network
      
volumes:
  volume-metricmind-alloy:

networks:
  metricmind-network:
    driver: bridge
